# Generated by Django 2.2.6 on 2021-01-23 07:22

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210114_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[users.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
